CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y

CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

# BLE: стабильность соединения между половинами
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5